{{- $root := . -}}
{{- $namespace := include "microservices.namespace" . -}}
{{- range $name, $svc := .Values.services }}
{{- $serviceName := default $name $svc.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  namespace: {{ $namespace }}
  labels:
{{ include "microservices.labels" (dict "root" $root "name" $serviceName) | indent 4 }}
spec:
  replicas: {{ $svc.replicaCount | default 1 }}
  selector:
    matchLabels:
{{ include "microservices.selectorLabels" (dict "name" $serviceName) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "microservices.labels" (dict "root" $root "name" $serviceName) | indent 8 }}
    spec:
      containers:
        - name: {{ $serviceName }}
          image: {{ $svc.image }}
          imagePullPolicy: {{ $svc.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ $svc.containerPort }}
          {{- with $svc.env }}
          env:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $svc.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}
{{- end }}

