{{- $root := . -}}
{{- $namespace := include "microservices.namespace" . -}}
{{- range $name, $svc := .Values.services }}
{{- $serviceName := default $name $svc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ $namespace }}
  labels:
{{ include "microservices.labels" (dict "root" $root "name" $serviceName) | indent 4 }}
spec:
  type: {{ $svc.serviceType | default "ClusterIP" }}
  selector:
{{ include "microservices.selectorLabels" (dict "name" $serviceName) | indent 4 }}
  ports:
    - name: http
      port: {{ $svc.servicePort | default $svc.containerPort }}
      targetPort: {{ $svc.targetPort | default $svc.containerPort }}
{{- end }}

