namespace: microservices

globalLabels:
  app.kubernetes.io/part-of: microservices

services:
  - name: service-a
    image: registry.k8s.io/echoserver:1.10
    replicaCount: 2
    containerPort: 8080
    servicePort: 80
    env:
      - name: SERVICE_NAME
        value: service-a
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
  - name: service-b
    image: nginx:1.25.3
    replicaCount: 2
    containerPort: 80
    servicePort: 80
    env:
      - name: SERVICE_NAME
        value: service-b
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

