apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app.kubernetes.io/name: service-b
    app.kubernetes.io/part-of: microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: service-b
  ports:
    - name: http
      port: 80
      targetPort: http

