apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices
resources:
  - service-a/deployment.yaml
  - service-a/service.yaml
  - service-b/deployment.yaml
  - service-b/service.yaml

